services:
  da_freecodecamp:
    container_name: da_freecodecamp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/work:delegated
    ports:
      - 8888:8888
    env_file:
      - .env
    command: "start-notebook.sh --NotebookApp.token="
    networks:
      - da_freecodecamp-network

networks:
  da_freecodecamp-network:
    driver: bridge

